<img src="img/python-logo-notext.svg"
     style="display:block;margin:auto;width:10%"/>
<h1 style="text-align:center;">Python: NumPy</h1>
<h2 style="text-align:center;">Coding Akademie München GmbH</h2>
<br/>
<div style="text-align:center;">Dr. Matthias Hölzl</div>
<div style="text-align:center;">Allaithy Raed</div>

# Listen als Vektoren und Matrizen

Wir können Python Listen verwenden um Vektoren darzustellen:

In [1]:
vector1 = [3, 2, 4]
vector2 = [8, 9, 7]

Es wäre dann möglich, Vektoroperationen auf derartigen Listen zu implementieren:

In [2]:
def vector_sum(v1, v2):
    assert len(v1) == len(v2)
    result = [0] * len(v1)
    for i in range(len(v1)):
        result[i] = v1[i] + v2[i]
    return result

In [3]:
vector_sum(vector1, vector2)

[11, 11, 11]

Matrizen könnten dann als "Listen von Listen" dargestellt werden:

In [4]:
matrix = [[1, 2, 3],
          [2, 3, 4],
          [3, 4, 5]]

Diese Implementierungsvariante hat jedoch einige Nachteile:
- Performanz
    - Speicher
    - Geschwindigkeit
    - Parallelisierbarkeit
- Interface
    - Zu allgemein
    - `*`, `+` auf Listen entspricht nicht den Erwartungen
    - ...
- ...

# NumPy

NumPy ist eine Bibliothek, die einen Datentyp für $n$-dimensionale Tensoren (`ndarray`) sowie effiziente Operationen darauf bereitstellt.
- Vektoren
- Matrizen
- Grundoperationen für Lineare Algebra
- Tensoren für Deep Learning

Fast alle anderen mathematischen und Data-Science-orientierten Bibliotheken für Python bauen auf NumPy auf (Pandas, SciPy, Statsmodels, TensorFlow, ...).

## Überblick

In [5]:
import numpy as np

In [6]:
v1 = np.array([3, 2, 4])
v2 = np.array([8, 9, 7])

In [7]:
type(v1)

numpy.ndarray

In [8]:
v1.dtype

dtype('int32')

In [9]:
v1 + v2

array([11, 11, 11])

In [10]:
v1 * v2 # Elementweises (Hadamard) Produkt

array([24, 18, 28])

In [11]:
v1.dot(v2)

70

In [12]:
v1.sum()

9

In [13]:
v1.mean()

3.0

In [14]:
v1.max()

4

In [15]:
v1.argmax()

2

In [16]:
m1 = np.array([[1, 2, 3],
               [4, 5, 6]])
m2 = np.array([[1, 0],
               [0, 1],
               [2, 3]])

In [17]:
# m1 + m2

In [18]:
m1.T + m2

array([[2, 4],
       [2, 6],
       [5, 9]])

In [19]:
m1.dot(m2)

array([[ 7, 11],
       [16, 23]])

## Erzeugen von NumPy Arrays

### Aus Python Listen

Durch geschachtelte Listen lassen sich Vektoren, Matrizen und Tensoren erzeugen:

In [20]:
vector = np.array([1, 2, 3, 4])
vector

array([1, 2, 3, 4])

In [21]:
vector.shape

(4,)

In [22]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
matrix.shape

(2, 3)

In [24]:
tensor = np.array([[[1, 2], [3, 4]],
                   [[5, 6], [7, 8]]])
tensor

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [25]:
tensor.shape

(2, 2, 2)

### Als Intervall bzw. Folge

In [26]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np.arange(10.0)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [28]:
np.arange(2, 10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
np.arange(3, 23, 5)

array([ 3,  8, 13, 18])

In [30]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [31]:
np.linspace(0.1, 1, 10)

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [32]:
np.arange(0.1, 1.1, 0.1)

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

### Konstant 0 oder 1

In [33]:
np.zeros(3)

array([0., 0., 0.])

In [34]:
np.zeros((3,))

array([0., 0., 0.])

In [35]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [36]:
np.ones(2)

array([1., 1.])

In [37]:
np.ones((4, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### Als Identitätsmatrix

In [38]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Aus Zufallsverteilung

Numpy bietet eine große Anzahl von möglichen [Generatoren und Verteilungen](https://docs.scipy.org/doc/numpy/reference/random/index.html) zum Erzeugen von Vektoren und Arrays mit zufälligen Elementen.

#### Setzen des Seed-Wertes

In [39]:
np.random.seed(101)

#### Gleichverteilt in [0, 1)

In [40]:
# Kompatibilität mit Matlab
np.random.seed(101)
np.random.rand(10)

array([0.51639863, 0.57066759, 0.02847423, 0.17152166, 0.68527698,
       0.83389686, 0.30696622, 0.89361308, 0.72154386, 0.18993895])

In [41]:
np.random.rand(4, 5)

array([[0.55422759, 0.35213195, 0.1818924 , 0.78560176, 0.96548322],
       [0.23235366, 0.08356143, 0.60354842, 0.72899276, 0.27623883],
       [0.68530633, 0.51786747, 0.04848454, 0.13786924, 0.18696743],
       [0.9943179 , 0.5206654 , 0.57878954, 0.73481906, 0.54196177]])

In [42]:
# Fehler
# np.random.rand((4, 5))

In [43]:
np.random.seed(101)
np.random.random(10)

array([0.51639863, 0.57066759, 0.02847423, 0.17152166, 0.68527698,
       0.83389686, 0.30696622, 0.89361308, 0.72154386, 0.18993895])

In [44]:
np.random.random((4, 5))

array([[0.55422759, 0.35213195, 0.1818924 , 0.78560176, 0.96548322],
       [0.23235366, 0.08356143, 0.60354842, 0.72899276, 0.27623883],
       [0.68530633, 0.51786747, 0.04848454, 0.13786924, 0.18696743],
       [0.9943179 , 0.5206654 , 0.57878954, 0.73481906, 0.54196177]])

#### Normalverteilte Zufallszahlen

In [45]:
# Kompatibilität mit Matlab
np.random.seed(101)
np.random.randn(10)

array([ 2.70684984,  0.62813271,  0.90796945,  0.50382575,  0.65111795,
       -0.31931804, -0.84807698,  0.60596535, -2.01816824,  0.74012206])

In [46]:
np.random.randn(4, 5)

array([[ 0.52881349, -0.58900053,  0.18869531, -0.75887206, -0.93323722],
       [ 0.95505651,  0.19079432,  1.97875732,  2.60596728,  0.68350889],
       [ 0.30266545,  1.69372293, -1.70608593, -1.15911942, -0.13484072],
       [ 0.39052784,  0.16690464,  0.18450186,  0.80770591,  0.07295968]])

In [47]:
# Fehler
# np.random.randn((4, 5))

In [48]:
np.random.seed(101)
np.random.standard_normal(10)

array([ 2.70684984,  0.62813271,  0.90796945,  0.50382575,  0.65111795,
       -0.31931804, -0.84807698,  0.60596535, -2.01816824,  0.74012206])

In [49]:
np.random.standard_normal((4, 5))

array([[ 0.52881349, -0.58900053,  0.18869531, -0.75887206, -0.93323722],
       [ 0.95505651,  0.19079432,  1.97875732,  2.60596728,  0.68350889],
       [ 0.30266545,  1.69372293, -1.70608593, -1.15911942, -0.13484072],
       [ 0.39052784,  0.16690464,  0.18450186,  0.80770591,  0.07295968]])

In [50]:
np.random.seed(101)
np.random.normal(10.0, 1.0, 10)

array([12.70684984, 10.62813271, 10.90796945, 10.50382575, 10.65111795,
        9.68068196,  9.15192302, 10.60596535,  7.98183176, 10.74012206])

In [51]:
np.random.normal(0.0, 1.0, (4, 5))

array([[ 0.52881349, -0.58900053,  0.18869531, -0.75887206, -0.93323722],
       [ 0.95505651,  0.19079432,  1.97875732,  2.60596728,  0.68350889],
       [ 0.30266545,  1.69372293, -1.70608593, -1.15911942, -0.13484072],
       [ 0.39052784,  0.16690464,  0.18450186,  0.80770591,  0.07295968]])

In [52]:
np.random.normal(10.0, 0.2, (2, 5))

array([[10.1277574 , 10.06592926,  9.9005792 ,  9.84918606,  9.81131872],
       [10.09695033,  9.97664534, 10.38035096, 10.04762539, 10.39933046]])

#### Multivariate Normalverteilung


In [53]:
means = np.array([0.0, 2.0, 1.0])
cov = np.array([[2.0, -1.0, 0.0],
                [-1.0, 2.0, -1.0],
                [0.0, -1.0, 2.0]])
np.random.multivariate_normal(means, cov, (3,))

array([[ 0.28588126,  0.08709108,  1.67948027],
       [-1.08625016,  1.91572865,  1.96571815],
       [ 0.20397352,  3.12493435,  2.50362519]])

#### Andere Verteilungen

In [54]:
np.random.binomial(10, 0.2, 88)

array([1, 1, 0, 2, 3, 2, 2, 2, 2, 1, 2, 2, 3, 0, 3, 3, 3, 2, 5, 1, 1, 1,
       0, 4, 0, 2, 2, 2, 0, 3, 2, 2, 3, 2, 3, 1, 2, 1, 5, 1, 1, 1, 4, 1,
       3, 4, 3, 2, 4, 3, 1, 3, 3, 2, 1, 3, 3, 1, 2, 1, 1, 2, 2, 2, 1, 1,
       1, 5, 0, 2, 2, 0, 4, 1, 2, 0, 3, 4, 3, 1, 4, 2, 1, 3, 1, 3, 0, 4])

In [55]:
np.random.multinomial(20, [1/6.0] * 6, 10)

array([[2, 4, 6, 6, 0, 2],
       [6, 3, 5, 2, 1, 3],
       [4, 3, 4, 3, 2, 4],
       [4, 5, 4, 2, 3, 2],
       [1, 3, 6, 5, 4, 1],
       [4, 5, 2, 2, 2, 5],
       [2, 0, 3, 8, 4, 3],
       [6, 3, 2, 2, 3, 4],
       [4, 5, 1, 4, 0, 6],
       [4, 3, 2, 4, 1, 6]])

Die [Dokumentation](https://docs.scipy.org/doc/numpy/reference/random/generator.html) enthält eine Liste aller Verteilungen und ihrer Parameter.

## Mini-Workshop

- Notebook `050x-NumPy`
- Abschnitt "Erzeugen von NumPy Arrays"


## Exkurs: Lösen von Gleichungssystemen

In [56]:
import scipy.linalg as linalg

a = np.array([[2., 1., 1.],
              [1., 3., 2.],
              [1., 0., 0.]])
b = np.array([4., 5., 6.])

In [57]:
lu = linalg.lu_factor(a)

In [58]:
lu

(array([[ 2. ,  1. ,  1. ],
        [ 0.5,  2.5,  1.5],
        [ 0.5, -0.2, -0.2]]),
 array([0, 1, 2], dtype=int32))

In [59]:
x = linalg.lu_solve(lu, b)

In [60]:
x

array([  6.,  15., -23.])

In [61]:
a.dot(x)

array([4., 5., 6.])

In [62]:
# Hermite'sche Matrix, positiv definit
a = np.array([[10., -1., 2., 0.],
             [-1., 11., -1., 3.],
             [2., -1., 10., -1.],
             [0., 3., -1., 8.]])
b= np.array([6., 25., -11., 15.])

In [63]:
cholesky = linalg.cholesky(a)

In [64]:
cholesky

array([[ 3.16227766, -0.31622777,  0.63245553,  0.        ],
       [ 0.        ,  3.3015148 , -0.24231301,  0.9086738 ],
       [ 0.        ,  0.        ,  3.08889696, -0.25245792],
       [ 0.        ,  0.        ,  0.        ,  2.6665665 ]])

In [65]:
cholesky.T.conj().dot(cholesky)

array([[10., -1.,  2.,  0.],
       [-1., 11., -1.,  3.],
       [ 2., -1., 10., -1.],
       [ 0.,  3., -1.,  8.]])

In [66]:
y = np.linalg.solve(cholesky.T.conj(), b)

In [67]:
x = np.linalg.solve(cholesky, y)

In [68]:
x

array([ 1.,  2., -1.,  1.])

In [69]:
a.dot(x)

array([  6.,  25., -11.,  15.])

## Attribute von Arrays

In [70]:
int_array = np.arange(36)
float_array = np.arange(36.0)

In [71]:
int_array.dtype

dtype('int32')

In [72]:
float_array.dtype

dtype('float64')

In [73]:
int_array.shape

(36,)

In [74]:
int_array.size

36

In [75]:
int_array.itemsize

4

In [76]:
float_array.itemsize

8

In [77]:
np.info(int_array)

class:  ndarray
shape:  (36,)
strides:  (4,)
itemsize:  4
aligned:  True
contiguous:  True
fortran:  True
data pointer: 0x25edf546b60
byteorder:  little
byteswap:  False
type: int32


In [78]:
np.info(float_array)

class:  ndarray
shape:  (36,)
strides:  (8,)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  True
data pointer: 0x25edf503ca0
byteorder:  little
byteswap:  False
type: float64


## Ändern von Shape und Größe

In [79]:
float_array.shape

(36,)

In [80]:
float_matrix = float_array.reshape((6, 6))

In [81]:
float_matrix

array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10., 11.],
       [12., 13., 14., 15., 16., 17.],
       [18., 19., 20., 21., 22., 23.],
       [24., 25., 26., 27., 28., 29.],
       [30., 31., 32., 33., 34., 35.]])

In [82]:
float_matrix.shape

(6, 6)

In [83]:
float_array.shape

(36,)

In [84]:
float_array.reshape(3, 12)

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.],
       [12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23.],
       [24., 25., 26., 27., 28., 29., 30., 31., 32., 33., 34., 35.]])

In [85]:
# Fehler
# float_array.reshape(4, 8)

In [86]:
float_array.reshape((4, 9), order='F')

array([[ 0.,  4.,  8., 12., 16., 20., 24., 28., 32.],
       [ 1.,  5.,  9., 13., 17., 21., 25., 29., 33.],
       [ 2.,  6., 10., 14., 18., 22., 26., 30., 34.],
       [ 3.,  7., 11., 15., 19., 23., 27., 31., 35.]])

In [87]:
np.resize(float_array, (4, 8))

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20., 21., 22., 23.],
       [24., 25., 26., 27., 28., 29., 30., 31.]])

In [88]:
float_array.shape

(36,)

In [89]:
np.resize(float_array, (4, 10))

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14., 15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24., 25., 26., 27., 28., 29.],
       [30., 31., 32., 33., 34., 35.,  0.,  1.,  2.,  3.]])

## Mini-Workshop

- Notebook `050x-NumPy`
- Abschnitt "Erzeugen von NumPy Arrays 2"


## Broadcasting von Operationen

Viele Operationen mit Skalaren werden Elementweise auf NumPy Arrays angewendet:

In [90]:
arr = np.arange(8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [91]:
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [92]:
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [93]:
arr ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49], dtype=int32)

In [94]:
2 ** arr

array([  1,   2,   4,   8,  16,  32,  64, 128], dtype=int32)

In [95]:
arr > 5

array([False, False, False, False, False, False,  True,  True])

## Minimum, Maximum, Summe, ...

In [96]:
np.random.seed(101)
vec = np.random.rand(10)
vec

array([0.51639863, 0.57066759, 0.02847423, 0.17152166, 0.68527698,
       0.83389686, 0.30696622, 0.89361308, 0.72154386, 0.18993895])

In [97]:
vec.max()

0.8936130796833973

In [98]:
vec.argmax()

7

In [99]:
vec.min()

0.028474226478096942

In [100]:
vec.argmin()

2

In [101]:
np.random.seed(101)
arr = np.random.rand(2, 5)
arr

array([[0.51639863, 0.57066759, 0.02847423, 0.17152166, 0.68527698],
       [0.83389686, 0.30696622, 0.89361308, 0.72154386, 0.18993895]])

In [102]:
arr.max()

0.8936130796833973

In [103]:
arr.argmax()

7

In [104]:
arr.min()

0.028474226478096942

In [105]:
arr.argmin()

2

## Mini-Workshop

- Notebook `050x-NumPy`
- Abschnitt "Extrema"


In [106]:
arr.reshape(arr.size)[arr.argmin()]

0.028474226478096942

In [107]:
arr[np.unravel_index(arr.argmin(), arr.shape)]

0.028474226478096942

In [108]:
arr

array([[0.51639863, 0.57066759, 0.02847423, 0.17152166, 0.68527698],
       [0.83389686, 0.30696622, 0.89361308, 0.72154386, 0.18993895]])

In [109]:
arr.sum()

4.918298056935911

In [110]:
arr.sum(axis=0)

array([1.35029549, 0.87763381, 0.92208731, 0.89306552, 0.87521594])

In [111]:
arr.sum(axis=1)

array([1.97233908, 2.94595898])

In [112]:
arr.mean()

0.49182980569359114

In [113]:
arr.mean(axis=0)

array([0.67514775, 0.4388169 , 0.46104365, 0.44653276, 0.43760797])

In [114]:
arr.mean(axis=1)

array([0.39446782, 0.5891918 ])

## Mini-Workshop

- Notebook `050x-NumPy`
- Abschnitt "Mittelwert"


## Exkurs: Einfache Monte Carlo Simulation

Mit der folgenden Monte Carlo Simulation kann eine Approximation von $\pi$ berechnet werden.

Die Grundidee ist zu berechnen, welcher Anteil an zufällig gezogenen Paaren aus Zahlen $(x, y)$, mit $x, y \sim SV[0, 1)$  (d.h., unabhängig und stetig auf $[0, 1)$ verteilt) eine $\ell^2$ Norm kleiner als 1 hat. Diese Zahl ist eine
Approximation von $\pi/4$.

Die folgende naive Implementiertung is in (fast) reinem Python geschrieben und verwendet NumPy nur zur Berechnung der Zufallszahlen.

In [141]:
def mc_pi_1(n):
    num_in_circle = 0
    for i in range(n):
        xy = np.random.random(2)
        if (xy ** 2).sum() < 1:
            num_in_circle += 1
    return num_in_circle * 4 / n

In [137]:
def test(mc_pi):
    np.random.seed(64)
    for n in [100, 10_000, 100_000, 1_000_000]:
        %time print(f"𝜋 ≈ {mc_pi(n)} ({n} iterations).")

In [147]:
# test(mc_pi_1)

Durch Just-in-Time Übersetzung mit Numba kann die Performance erheblich gesteigert werden:

In [149]:
import numba
mc_pi_1_nb = numba.jit(mc_pi_1)

In [150]:
test(mc_pi_1_nb)

𝜋 ≈ 3.12 (100 iterations).
Wall time: 540 ms
𝜋 ≈ 3.1704 (10000 iterations).
Wall time: 3 ms
𝜋 ≈ 3.14052 (100000 iterations).
Wall time: 26 ms
𝜋 ≈ 3.13954 (1000000 iterations).
Wall time: 201 ms


Die folgende Implementierung verwendet die Vektorisierungs-Features von NumPy:

In [139]:
def mc_pi_2(n):
    x = np.random.random(n)
    y = np.random.random(n)
    return ((x ** 2 + y ** 2) < 1).sum() * 4 / n

In [156]:
# test(mc_pi_2)

𝜋 ≈ 3.32 (100 iterations).
Wall time: 0 ns
𝜋 ≈ 3.1484 (10000 iterations).
Wall time: 999 µs
𝜋 ≈ 3.14004 (100000 iterations).
Wall time: 3 ms
𝜋 ≈ 3.140744 (1000000 iterations).
Wall time: 37 ms


In [166]:
# %time mc_pi_2(100_000_000)

Wall time: 2.98 s


3.14162228

Auch bei dieser Version können mit Numba Performance-Steigerungen erzielt werden, aber in deutlich geringerem Ausmaß:

In [160]:
mc_pi_2_nb = numba.jit(mc_pi_2)

In [161]:
# test(mc_pi_2_nb)

In [167]:
# %time mc_pi_2_nb(100_000_000)

Wall time: 1.88 s


3.14154536

## Mini-Workshop

- Notebook `050x-NumPy`
- Abschnitt "Roulette"


## Indizieren von NumPy Arrays

In [ ]:
vec = np.arange(10)

In [ ]:
vec

In [ ]:
vec[3]

In [ ]:
vec[3:8]

In [ ]:
vec[-1]

In [ ]:
arr = np.arange(24).reshape(4, 6)

In [ ]:
arr

In [ ]:
arr[1]

In [ ]:
arr[1][2]

In [ ]:
arr[1, 2]

In [ ]:
arr

In [ ]:
arr[1:3]

In [ ]:
arr[1:3][2:4]

In [ ]:
arr[1:3, 2:4]

In [ ]:
arr[:, 2:4]

In [ ]:
# Vorsicht!
arr[: 2:4]

In [ ]:
arr[:, 1:6:2]

## Broadcasting auf Slices

In NumPy Arrays werden Operationen oftmals auf Elemente (oder Unterarrays) "gebroadcastet":

In [ ]:
arr = np.ones((3, 3))

In [ ]:
arr[1:, 1:] = 2.0

In [ ]:
arr

In [ ]:
lst = [1, 2, 3]
vec = np.array([1, 2, 3])

In [ ]:
lst[:] = [99]

In [ ]:
vec[:] = [99]

In [ ]:
lst

In [ ]:
vec

In [ ]:
vec[:] = 11
vec

### Vorsicht beim `lst[:]` Idiom! 

In [ ]:
lst1 = list(range(10))
lst2 = lst1[:]
vec1 = np.arange(10)
vec2 = vec1[:]

In [ ]:
lst1[:] = [22] * 10
lst1

In [ ]:
lst2

In [ ]:
vec1[:] = 22
vec1

In [ ]:
vec2

In [ ]:
vec1 = np.arange(10)
vec2 = vec1.copy()

In [ ]:
vec1[:] = 22
vec1

In [ ]:
vec2

## Bedingte Selektion

NumPy Arrays können als Index auch ein NumPy Array von Boole'schen Werten erhalten, das den gleichen Shape hat wie das Array.

Dadurch werden die Elemente selektiert, an deren Position der Boole'sche Vektor den Wert `True` hat und als Vektor zurückgegeben.

In [ ]:
vec = np.arange(8)
bool_vec = (vec % 2 == 0)

In [ ]:
vec[bool_vec]

In [ ]:
arr = np.arange(8).reshape(2, 4)
bool_arr = (arr % 2 == 0)
bool_arr

In [ ]:
arr[bool_arr]

In [ ]:
# Fehler!
# arr[bool_vec]

In [ ]:
vec[vec % 2 > 0]

In [ ]:
arr[arr < 5]

### Boole'sche Operationen auf NumPy Arrays

In [ ]:
bool_vec

In [ ]:
neg_vec = np.logical_not(bool_vec)

In [ ]:
bool_vec & neg_vec

In [ ]:
bool_vec | neg_vec

## Universelle NumPy Operationen

NumPy bietet viele "universelle" Funktionen an, die auf NumPy Arrays, Listen und Zahlen angewendet werden können:

In [199]:
vec1 = np.random.randn(5)
vec2 = np.random.randn(5)
list1 = list(vec1)
list2 = list(vec2)

In [200]:
vec1

array([-2.12409169, -0.2112447 , -0.34279885, -1.09405329,  1.28688411])

In [201]:
list1

[-2.1240916909350913,
 -0.21124470440763113,
 -0.34279885219340855,
 -1.0940532877551732,
 1.286884113628861]

In [202]:
np.sin(vec1)

array([-0.85079745, -0.2096771 , -0.33612441, -0.88849421,  0.95996692])

In [203]:
np.sin(list1)

array([-0.85079745, -0.2096771 , -0.33612441, -0.88849421,  0.95996692])

In [210]:
import math
np.sin(math.pi)

1.2246467991473532e-16

In [213]:
np.sum(vec1)

-2.485304421662443

In [215]:
np.sum(list1)

-2.485304421662443

In [216]:
np.mean(vec1)

-0.4970608843324886

In [219]:
np.median(vec1)

-0.34279885219340855

In [222]:
np.std(vec1)

1.1217465484142257

In [223]:
np.greater(vec1, vec2)

array([False,  True, False, False,  True])

In [225]:
np.greater(list1, list2)

array([False,  True, False, False,  True])

In [226]:
np.greater(vec1, list2)

array([False,  True, False, False,  True])

In [208]:
np.maximum(vec1, vec2)

array([ 0.76954762, -0.2112447 ,  1.14925762, -0.39975127,  1.28688411])

In [227]:
np.maximum(list1, list2)

array([ 0.76954762, -0.2112447 ,  1.14925762, -0.39975127,  1.28688411])

In [228]:
np.maximum(list1, vec2)

array([ 0.76954762, -0.2112447 ,  1.14925762, -0.39975127,  1.28688411])

Eine vollständige Liste sowie weitere Dokumentation findet man [hier](https://docs.scipy.org/doc/numpy/reference/ufuncs.html).