# Erzeugen von NumPy Arrays

In [2]:
import numpy as np

Erzeugen Sie folgende NumPy Arrays:

```python
array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```

In [3]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

```python
array([0.  , 1.25, 2.5 , 3.75, 5.  ])
```

In [4]:
np.linspace(0,5,5)

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

```python
array([ 1,  3, 12, 92])
```

In [5]:
np.array([1, 3, 12, 92])

array([ 1,  3, 12, 92])

```python
array([[1, 2, 3, 4],
       [5, 6, 7, 8]])
```

In [6]:
np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

```python
array([[[0, 2, 4, 6],
        [1, 3, 5, 7]],

       [[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[9, 8, 7, 6],
        [5, 4, 3, 2]]])
```

In [33]:
np.array([[[0, 2, 4, 6], [1, 3, 5, 7]],
          [[1, 2, 3, 4], [5, 6, 7, 8]],
          [[9, 8, 7, 6], [5, 4, 3, 2]]])

array([[[0, 2, 4, 6],
        [1, 3, 5, 7]],

       [[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[9, 8, 7, 6],
        [5, 4, 3, 2]]])

In [34]:
np.array([[range(0, 7, 2), range(1, 8, 2)],
          [range(1, 5), range(5, 9)],
          [range(9, 5, -1), range(5, 1, -1)]])

array([[[0, 2, 4, 6],
        [1, 3, 5, 7]],

       [[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[9, 8, 7, 6],
        [5, 4, 3, 2]]])

Ein $2\times 8$ Array, das gleichverteilte Zufallszahlen in $[0, 1)$ enthält.

In [8]:
np.random.rand(2, 8)

array([[0.37899223, 0.27107634, 0.41871954, 0.54306131, 0.20675262,
        0.83592622, 0.52243164, 0.300828  ],
       [0.18326871, 0.80786993, 0.252885  , 0.05716423, 0.44726562,
        0.16510343, 0.58092779, 0.52934666]])

```python
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])
```

In [9]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Einen Vektor der Länge 5, der standard-normalverteilte Zahlen enthält.

In [10]:
np.random.standard_normal(5)

array([ 0.30717542, -1.04813037, -0.43493496,  2.30301174, -2.2457551 ])

Ein $3 \times 4$ Array, das normalverteilte Zahlen mit Mittelwert $5$ und Standardabweichung $0.5$ enthält.

In [11]:
np.random.normal(5, 0.5, (3, 4))

array([[4.90481929, 4.73622907, 6.00756019, 4.50236499],
       [5.55582066, 4.24536343, 5.1462687 , 5.08483019],
       [4.70492212, 5.49413091, 4.50326465, 4.43631863]])

## Gleichungssysteme

Lösen Sie folgendes Gleichungssystem:

$x_1 - x_2 + 2x_3 = 6$

$2x_1 + 3x_2 + 2x_3 = 8$

$3x_1 + 2x_2 + x_3 = 8$

In [27]:
a = np.array([[1., -1., 2.],
              [2.,  3., 2.],
              [3.,  2., 1.]])
b = np.array([6., 8., 8.])

In [29]:
import scipy.linalg as linalg
lu = linalg.lu_factor(a)

In [30]:
x = linalg.lu_solve(lu, b)

In [31]:
x

array([2., 0., 2.])

In [32]:
a.dot(x)

array([6., 8., 8.])

# Erzeugen von NumPy Arrays 2

Erzeugen Sie das folgende NumPy Array:

```python
array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30],
       [32, 34, 36, 38]])
```

In [12]:
np.arange(0, 40, 2).reshape(5, 4)

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30],
       [32, 34, 36, 38]])

Erzeugen Sie das folgende NumPy Array:

```python
array([[10, 19, 28, 37, 46, 55],
       [13, 22, 31, 40, 49, 58],
       [16, 25, 34, 43, 52, 61]])
```

In [13]:
np.arange(10, 64, 3).reshape(3, 6, order="F")

array([[10, 19, 28, 37, 46, 55],
       [13, 22, 31, 40, 49, 58],
       [16, 25, 34, 43, 52, 61]])

# Extrema

Erzeugen Sie einen Vektor der Länge 100 mit Zufallswerten, die im Intervall
$[10, 20)$ gleichverteilt sind. 

Berechnen Sie Minimum und Maximum der im Vektor
enthaltenen Werte sowie die Positionen von Minimum und Maximum.

In [14]:
vec = np.random.random(100) * 10 + 10
vec[:10]

array([13.07645729, 11.06235018, 10.16681816, 14.62367025, 18.46884783,
       19.37906256, 14.59068671, 14.2811849 , 17.37788074, 14.57235891])

In [15]:
vec.min()

10.034784034070142

In [16]:
vec.argmin()

49

In [17]:
vec.max()

19.803678096902438

In [18]:
vec.argmax()

63

# Mittelwert

Erzeugen Sie ein $6 \times 8$ Array, das standardverteilten Zahlen mit
Mittelwert $2$ und Standardabweichung $1$ enthält.



In [19]:
my_array = np.random.normal(2.0, 1.0, (6, 8))

Berechnen Sie den Mittelwert aller darin vorkommenden Werte.


In [20]:
my_array.mean()

2.0174821133441068

Berechnen Sie die zeilen- und spaltenweisen Mittelwerte.

In [21]:
my_array.mean(axis=0)

array([1.49639855, 1.9351355 , 2.03724751, 2.34848432, 2.28417489,
       2.01256044, 1.33768357, 2.68817213])

In [22]:
my_array.mean(axis=1)

array([2.27823953, 2.32220561, 1.84725536, 2.34430015, 1.85803375,
       1.45485828])

Berechnen Sie den Mittelwert aller vorkommenden Werte ohne Verwendung der
Methode `mean()`.

In [23]:
mean = my_array.sum() / my_array.size
mean

2.0174821133441068

Berechnen Sie die zeilen- und spaltenweisen Mittelwerte ohne Verwendung der
Methode `mean()`.

In [24]:
my_array.sum(axis=0) / my_array.shape[0]

array([1.49639855, 1.9351355 , 2.03724751, 2.34848432, 2.28417489,
       2.01256044, 1.33768357, 2.68817213])

In [25]:
my_array.sum(axis=1) / my_array.shape[1]

array([2.27823953, 2.32220561, 1.84725536, 2.34430015, 1.85803375,
       1.45485828])

# Roulette

Analysieren Sie die Gewinnerwartung eines Spielers in folgender vereinfachter Form eines Roulettespiels mittels Monte Carlo Simulation:

- Der Kessel ist in 36 Zahlen unterteilt.
- Der Spieler wählt eine der Zahlen 1 bis 36 und wettet 1 Euro.
- Fällt die Kugel auf die gewählte Zahl, so erhält der Spieler seinen Einsatz plus 35 Euro zurück.
- Andernfalls verliert der Spieler seinen Einsatz.

Schreiben Sie eine Version der Simulation mit `for`-Schleife in Python und testen Sie die Performance dieser Version vor und nach Kompilierung mit Numba. Schreiben Sie dann eine vektorisierte Version und testen Sie deren Performance in beiden Fällen.

*Hinweise:* 
- Die NumPy Bibliothek enthält eine Funktion `np.random.randint(low, high, size=None)`, mit der Sie ein Array mit Shape `size` erzeugen können, das gleichverteilte Zufallszahlen zwischen `low` (inklusive) und `high` (exklusive) enthält.
- Wird `np.random.randint()` mit nur zwei Argumenten aufgerufen, so gibt es eine einzige Zahl zurück.
- Die NumPy Bibliothek enthält eine Funtion `np.random.binomial(n, p, size=None)`, mit der Sie binomialverteilte Zufallszahlen erzeugen können.

In [3]:
import numpy as np

In [42]:
def roulette1(n):
    # Wir können davon ausgehen, dass der Spieler immer auf die 1 wettet
    money_spent = 0
    money_won = 0
    for i in range(n):
        money_spent += 1
        if np.random.randint(1, 37) == 1:
            money_won += 36
    return (money_won - money_spent) / n

In [43]:
def test_roulette(roulette):
    np.random.seed(123)
    for n in [1000, 100_000, 1_000_000]:
        %time print(f"Gewinnerwartung ist {100 * roulette(n):.1f}% ({n} Versuche)")

In [56]:
test_roulette(roulette1)

Gewinnerwartung ist -13.6% (1000 Versuche)
Wall time: 7 ms
Gewinnerwartung ist 1.7% (100000 Versuche)
Wall time: 618 ms
Gewinnerwartung ist -0.9% (1000000 Versuche)
Wall time: 6.01 s


In [57]:
import numba
roulette1_nb = numba.jit(roulette1)

In [58]:
test_roulette(roulette1_nb)

Gewinnerwartung ist 18.8% (1000 Versuche)
Wall time: 74 ms
Gewinnerwartung ist 1.2% (100000 Versuche)
Wall time: 1 ms
Gewinnerwartung ist -0.3% (1000000 Versuche)
Wall time: 12 ms


In [59]:
def roulette2(n):
    money_spent = np.ones(n)
    money_won = np.random.binomial(1, 1.0/36.0, n) * 36
    return (money_won - money_spent).sum() / n

In [61]:
test_roulette(roulette2)

Gewinnerwartung ist 4.4% (1000 Versuche)
Wall time: 999 µs
Gewinnerwartung ist 1.7% (100000 Versuche)
Wall time: 2 ms
Gewinnerwartung ist 0.1% (1000000 Versuche)
Wall time: 27 ms


In [62]:
roulette2_nb = numba.jit(roulette2)

In [63]:
test_roulette(roulette2_nb)

Gewinnerwartung ist -17.2% (1000 Versuche)
Wall time: 252 ms
Gewinnerwartung ist 4.9% (100000 Versuche)
Wall time: 3 ms
Gewinnerwartung ist 0.4% (1000000 Versuche)
Wall time: 34 ms


In [64]:
def roulette3(n):
    money_spent = n
    money_won = np.random.binomial(n, 1.0/36.0) * 36
    return (money_won - money_spent) / n

In [65]:
test_roulette(roulette3)

Gewinnerwartung ist 8.0% (1000 Versuche)
Wall time: 0 ns
Gewinnerwartung ist 0.6% (100000 Versuche)
Wall time: 0 ns
Gewinnerwartung ist 0.0% (1000000 Versuche)
Wall time: 0 ns


In [66]:
roulette3_nb = numba.jit(roulette3)

In [67]:
test_roulette(roulette3_nb)

Gewinnerwartung ist 0.8% (1000 Versuche)
Wall time: 69 ms
Gewinnerwartung ist 1.8% (100000 Versuche)
Wall time: 999 µs
Gewinnerwartung ist 0.4% (1000000 Versuche)
Wall time: 0 ns


In [70]:
roulette3(100_000_000)

-0.00032572