# Erzeugen von NumPy Arrays

In [ ]:
import numpy as np

Erzeugen Sie folgende NumPy Arrays:

```python
array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```

In [ ]:
np.arange(10)

```python
array([0.  , 1.25, 2.5 , 3.75, 5.  ])
```

In [ ]:
np.linspace(0, 5, 5)

```python
array([ 1,  3, 12, 92])
```

In [ ]:
np.array([1, 3, 12, 92])

```python
array([[1, 2, 3, 4],
       [5, 6, 7, 8]])
```

In [ ]:
np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

```python
array([[[0, 2, 4, 6],
        [1, 3, 5, 7]],

       [[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[9, 8, 7, 6],
        [5, 4, 3, 2]]])
```

In [ ]:
np.array([[[0, 2, 4, 6], [1, 3, 5, 7]],
          [[1, 2, 3, 4], [5, 6, 7, 8]],
          [[9, 8, 7, 6], [5, 4, 3, 2]]])

In [ ]:
np.array([[range(0, 7, 2), range(1, 8, 2)],
          [range(1, 5), range(5, 9)],
          [range(9, 5, -1), range(5, 1, -1)]])

Ein $2\times 8$ Array, das gleichverteilte Zufallszahlen in $[0, 1)$ enthält.

In [ ]:
np.random.rand(2, 8)

```python
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])
```

In [ ]:
np.eye(3)

Einen Vektor der Länge 5, der standard-normalverteilte Zahlen enthält.

In [ ]:
np.random.standard_normal(5)

Ein $3 \times 4$ Array, das normalverteilte Zahlen mit Mittelwert $5$ und Standardabweichung $0.5$ enthält.

In [ ]:
np.random.normal(5, 0.5, (3, 4))

## Gleichungssysteme

Lösen Sie folgendes Gleichungssystem:

$x_1 - x_2 + 2x_3 = 6$

$2x_1 + 3x_2 + 2x_3 = 8$

$3x_1 + 2x_2 + x_3 = 8$

In [ ]:
a = np.array([[1., -1., 2.],
              [2., 3., 2.],
              [3., 2., 1.]])
b = np.array([6., 8., 8.])

In [ ]:
import scipy.linalg as linalg

lu = linalg.lu_factor(a)

In [ ]:
x = linalg.lu_solve(lu, b)

In [ ]:
x

In [ ]:
a.dot(x)

# Erzeugen von NumPy Arrays 2

Erzeugen Sie das folgende NumPy Array:

```python
array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30],
       [32, 34, 36, 38]])
```

In [ ]:
np.arange(0, 40, 2).reshape(5, 4)

Erzeugen Sie das folgende NumPy Array:

```python
array([[10, 19, 28, 37, 46, 55],
       [13, 22, 31, 40, 49, 58],
       [16, 25, 34, 43, 52, 61]])
```

In [ ]:
np.arange(10, 64, 3).reshape(3, 6, order="F")

# Extrema

Erzeugen Sie einen Vektor der Länge 100 mit Zufallswerten, die im Intervall
$[10, 20)$ gleichverteilt sind. 

Berechnen Sie Minimum und Maximum der im Vektor
enthaltenen Werte sowie die Positionen von Minimum und Maximum.

In [ ]:
vec = np.random.random(100) * 10 + 10
vec[:10]

In [ ]:
vec.min()

In [ ]:
vec.argmin()

In [ ]:
vec.max()

In [ ]:
vec.argmax()

# Mittelwert

Erzeugen Sie ein $6 \times 8$ Array, das standardverteilten Zahlen mit
Mittelwert $2$ und Standardabweichung $1$ enthält.



In [ ]:
my_array = np.random.normal(2.0, 1.0, (6, 8))

Berechnen Sie den Mittelwert aller darin vorkommenden Werte.


In [ ]:
my_array.mean()

Berechnen Sie die zeilen- und spaltenweisen Mittelwerte.

In [ ]:
my_array.mean(axis=0)

In [ ]:
my_array.mean(axis=1)

Berechnen Sie den Mittelwert aller vorkommenden Werte ohne Verwendung der
Methode `mean()`.

In [ ]:
mean = my_array.sum() / my_array.size
mean

Berechnen Sie die zeilen- und spaltenweisen Mittelwerte ohne Verwendung der
Methode `mean()`.

In [ ]:
my_array.sum(axis=0) / my_array.shape[0]

In [ ]:
my_array.sum(axis=1) / my_array.shape[1]

# Roulette

Analysieren Sie die Gewinnerwartung eines Spielers in folgender
vereinfachter Form eines Roulettespiels mittels Monte Carlo Simulation:

- Der Kessel ist in 36 Zahlen unterteilt.
- Der Spieler wählt eine der Zahlen 1 bis 36 und wettet 1 Euro.
- Fällt die Kugel auf die gewählte Zahl, so erhält der Spieler seinen Einsatz
  plus 35 Euro zurück.
- Andernfalls verliert der Spieler seinen Einsatz.

Schreiben Sie eine Version der Simulation mit `for`-Schleife in Python und
testen Sie die Performance dieser Version vor und nach Kompilierung mit
Numba. Schreiben Sie dann eine vektorisierte Version und testen Sie deren
Performance in beiden Fällen.

*Hinweise:* 
- Die NumPy Bibliothek enthält eine Funktion
  `np.random.randint(low, high, size=None)`, mit der Sie ein Array mit Shape
  `size` erzeugen können, das gleichverteilte Zufallszahlen zwischen `low`
  (inklusive) und `high` (exklusive) enthält.
- Wird `np.random.randint()` mit nur zwei Argumenten aufgerufen, so gibt es
  eine einzige Zahl zurück.
- Die NumPy Bibliothek enthält eine Funtion
  `np.random.binomial(n, p, size=None)`, mit der Sie binomialverteilte
  Zufallszahlen erzeugen können.

In [ ]:
import numpy as np

In [ ]:
def roulette1(n):
    # Wir können davon ausgehen, dass der Spieler immer auf die 1 wettet
    money_spent = 0
    money_won = 0
    for i in range(n):
        money_spent += 1
        if np.random.randint(1, 37) == 1:
            money_won += 36
    return (money_won - money_spent) / n

In [ ]:
def test_roulette(roulette):
    np.random.seed(123)
    for n in [1000, 100_000, 1_000_000]:
        %time print(f"Gewinnerwartung ist {100 * roulette(n):.1f}% ({n} Versuche)")
        print(f"Gewinnerwartung ist {100 * roulette(n):.1f}% ({n} Versuche)")

In [ ]:
test_roulette(roulette1)

In [ ]:
import numba

roulette1_nb = numba.jit(roulette1)

In [ ]:
test_roulette(roulette1_nb)

In [ ]:
def roulette2(n):
    money_spent = np.ones(n)
    money_won = np.random.binomial(1, 1.0 / 36.0, n) * 36
    return (money_won - money_spent).sum() / n

In [ ]:
test_roulette(roulette2)

In [ ]:
roulette2_nb = numba.jit(roulette2)

In [ ]:
test_roulette(roulette2_nb)

In [ ]:
def roulette3(n):
    money_spent = n
    money_won = np.random.binomial(n, 1.0 / 36.0) * 36
    return (money_won - money_spent) / n

In [ ]:
test_roulette(roulette3)

In [ ]:
roulette3_nb = numba.jit(roulette3)

In [ ]:
test_roulette(roulette3_nb)

In [ ]:
roulette3(100_000_000)