<img src="img/python-logo-notext.svg"
     style="display:block;margin:auto;width:10%"/>
<br>
<div style="text-align:center; font-size:200%;"><b>Vertiefung zu Listen</b></div>
<br/>
<div style="text-align:center;">Dr. Matthias Hölzl</div>

# Listen

Wiederholung:

- Listen-Literale werden in eckige Klammern eingeschlossen
- Andere Sequenzen können mittels `list` in Listen umgewandelt werden

In [1]:
["a", "b", "c"]

['a', 'b', 'c']

In [3]:
list("abc")

['a', 'b', 'c']

In [5]:
for x in [1, 2, 3]:
    print(x)

1
2
3


In [6]:
range(1, 4)

range(1, 4)

In [7]:
list(range(1, 4))

[1, 2, 3]

In [8]:
range(4)

range(0, 4)

In [9]:
list(range(4))

[0, 1, 2, 3]

In [11]:
list(range(1, 9, 2))

[1, 3, 5, 7]

In [13]:
for x in range(1, 4):
    print(x)

1
2
3


In [16]:
[x * 2 for x in [2, 4, 5, 6]]

[4, 8, 10, 12]

In [17]:
import numpy as np

In [18]:
my_array = np.array([2, 3, 4, 5, 6])

In [19]:
my_array

array([2, 3, 4, 5, 6])

In [21]:
my_array * 2

array([ 4,  6,  8, 10, 12])

In [22]:
my_array ** 2

array([ 4,  9, 16, 25, 36], dtype=int32)

In [23]:
2 ** my_array

array([ 4,  8, 16, 32, 64], dtype=int32)

## Mini-Workshop

- Notebook `workshop_060_introduction_part2`
- Abschnitt "Ausgabe von Quadratzahlen"

## Eigenschaften von Listen

- Listen können beliebige Python-Werte speichern
- Elemente in einer Liste haben eine feste Reihenfolge
- Auf Elemente einer Liste kann mit einem Index zugegriffen werden
- Listen können modifiziert werden

Listen können Elemente mit verschiedenen Typen enthalten, die meisten Listen
enthalten aber Elemente eines einzigen Typs.

In [24]:
stringliste = ["a", "b", "c"]

In [25]:
stringliste[0]

'a'

In [26]:
stringliste[-1]

'c'

### Überprüfen, ob ein Element in einer Liste enthalten ist

In [27]:
2 in [1, 2, 3]

True

In [29]:
not (2 in [1, 2, 3])

False

In [31]:
if 2 not in [1, 2, 3]:
    print("Not present")

### Finden der Position eines Elements

In [37]:
stringliste

['a', 'b', 'c']

In [38]:
stringliste.index("a")

0

In [40]:
stringliste.index("b")

1

In [42]:
stringliste.index("c")

2

In [44]:
stringliste.index("d")

ValueError: 'd' is not in list

In [46]:
stringliste[stringliste.index("a")]

'a'

In [33]:
my_list = ["a", "b", "c", "d", "b", "d", "b"]

In [47]:
my_index = my_list.index("b")
print(my_index)
my_list[my_index]

1


'b'

In [36]:
[1, 2, 3].index(4)

ValueError: 4 is not in list

## Micro-Workshop:

Die Methode `index` wirft eine Exception, wenn das gesuchte Objekt nicht in
der Liste vorkommt. Schreiben Sie eine Funktion
```
find(element, a_list)
```

- die einen Index zurückgibt, falls das Element `element` in der Liste
  vorkommt, und
- die `None` zurückgibt, falls es nicht vorkommt

In [61]:
def find(element, a_list):
    if element in a_list:
        return a_list.index(element)
    else:
        return None

In [62]:
my_list = ["a", "b", "c", "d", "e"]

In [63]:
find("a", my_list)

0

In [64]:
find("d", my_list)

3

In [65]:
find("x", my_list) == None

True

### Modifikation von Elementen

In [73]:
stringliste

['A', 'b', 'c', 'D']

In [74]:
stringliste[0] = "A"

In [75]:
stringliste

['A', 'b', 'c', 'D']

### Einfügen und Anhängen von Elementen

In [76]:
stringliste = ["A", "b", "c"]

In [77]:
stringliste.append("D")

In [78]:
stringliste

['A', 'b', 'c', 'D']

In [79]:
stringliste + ["E", "F"]

['A', 'b', 'c', 'D', 'E', 'F']

In [80]:
stringliste

['A', 'b', 'c', 'D']

In [81]:
stringliste.extend(["E", "F"])

In [82]:
stringliste

['A', 'b', 'c', 'D', 'E', 'F']

In [83]:
stringliste.insert(0, "ANFANG")

In [84]:
stringliste

['ANFANG', 'A', 'b', 'c', 'D', 'E', 'F']

In [85]:
stringliste.insert(-1, "ENDE")

In [86]:
stringliste

['ANFANG', 'A', 'b', 'c', 'D', 'E', 'ENDE', 'F']

In [87]:
stringliste.insert(len(stringliste), "XXX")

In [88]:
stringliste

['ANFANG', 'A', 'b', 'c', 'D', 'E', 'ENDE', 'F', 'XXX']

### Entfernen von Elementen

In [89]:
stringliste = ["ANFANG", "A", "Y", "b", "c", "D", "E", "ENDE", "F"]
stringliste[7]

'ENDE'

In [90]:
stringliste.pop(7)
# del stringliste[7]

'ENDE'

In [91]:
stringliste

['ANFANG', 'A', 'Y', 'b', 'c', 'D', 'E', 'F']

### Länge einer Liste

In [93]:
stringliste

['ANFANG', 'A', 'Y', 'b', 'c', 'D', 'E', 'F']

In [94]:
len(stringliste)

8

In [96]:
stringliste[len(stringliste) - 1]

'F'

In [ ]:
stringliste

## Mini-Workshop

- Notebook `workshop_100_lists_part2`
- Abschnitt "Farben"


## Erzeugen von Listen

Durch den Multiplikationsoperator `*` können die Elemente einer Liste
wiederholt werden:

In [98]:
[1, 2] * 3

[1, 2, 1, 2, 1, 2]

In [99]:
3 * ["a", "b"]

['a', 'b', 'a', 'b', 'a', 'b']

In [100]:
[1] * 10

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

## Slicing

Mit der Notation `liste[m:n]` kann man eine "Teilliste" von `liste`
extrahieren.

- Das erste Element ist `liste[m]`
- Das letzte Element ist `liste[n-1]`

In [102]:
stringliste = ["a", "b", "c", "d", "e"]

In [105]:
stringliste[1:3]

['b', 'c']

In [112]:
stringliste[1:1]

[]

In [114]:
stringliste[0:1000]

['a', 'b', 'c', 'd', 'e']

In [116]:
stringliste[:3]

['a', 'b', 'c']

In [117]:
stringliste[1:]

['b', 'c', 'd', 'e']

In [118]:
stringliste[:]

['a', 'b', 'c', 'd', 'e']

## Mini-Workshop

- Notebook `workshop_100_lists_part2`
- Abschnitt "Slicing"


## Zuweisung an Slices

Man kann Werte an Slices zuweisen:

In [120]:
my_list = [1, 2, 3, 4]
my_list[1:3]

[2, 3]

In [122]:
my_list[1:3] = [20, 30, 40, 50]
my_list

[1, 20, 30, 40, 50, 4]

In [124]:
my_list[2:4] = []
my_list

[1, 20, 50, 4]

In [127]:
my_list[2:2]

[]

In [128]:
my_list[2:2] = ["x"]
my_list

[1, 20, 'x', 50, 4]

In [129]:
my_list[1:1] = ["a", "b", "c"]
my_list

[1, 'a', 'b', 'c', 20, 'x', 50, 4]

In [130]:
my_list[:] = [11, 22, 33]
my_list

[11, 22, 33]

## Slices als Objekte

Slices sind selber Python Objekte. Außerhalb der Indexing-Operation `[]`
können sie allerdings nicht mit der Notation `a:b` erzeugt werden, sondern
mit der Konstruktor-Funktion `slice()`.

In [ ]:
my_list = [1, 2, 3, 4, 5, 6]
print(my_list[2:4])

In [ ]:
print(my_list[:3])


Die `indices()`-Methode eines Slice-Objekts kann dazu verwendet werden zu
bestimmen, welche Indizes das Slice enthält:

In [ ]:
my_slice = slice(None, 3)
print(my_slice.indices(len(my_list)))


Damit können wir eine Funktion schreiben, die alle Elemente eines Slices
durch einen Wert ersetzt:

In [ ]:
def replace_with(my_list, my_slice, value):
    import math

    start, stop, stride = my_slice.indices(len(my_list))
    num_values = math.ceil((stop - start) / stride)
    my_list[my_slice] = [value] * num_values

In [ ]:
my_list = [1, 2, 3, 4, 5, 6]
my_slice = slice(2, 6)
replace_with(my_list, my_slice, 8)
my_list